
## Improving my NumPy skill with materials from Hamoye.AI and Huntsman School of Business, Utah State University 

# NumPy 

My Practice explored:

0. General First notice
1. Numpy arrays
2. Numpy indexing and extraction
3. Numpy operations



## 0. General First notice

Because i am using Jupyter Lab and not Jupyter Notebook, 
NB: 
Use ctrl + b to hide the fle directory to have a bigger code tab for full and better view
Use ctrl + i to bring the contextual help window, window which will help explain the module/library documentation for functions, objects called with what type of parameter to use and how it should be used.

In [2]:
#Importing the numpy module
import numpy as np #a convention is to import as np

In [3]:
#A NumPy array has a grid of values all of which are of the same data type, mostly integers and floats. 
#These arrays can also be created from Python lists.
example1 = [2,0,2,3] #Like it is here, created an array from python list
print(type(example1)) #TO confirm if its created from list
#i Used the type function to check the datatype of the value stored in the arrayexample folder which print class list.

<class 'list'>


In [4]:
#NumPy has ndarray (i.e the 'nd.array()')as its basic data structure used to handle arrays and matrices. 
example2 = np.array(example1) #Created another variable to handle the array (list) created earlier 
print(type(example2)) #This print the data type (data structure) of the example2 variable  which is numpy.ndarray

<class 'numpy.ndarray'>


In [5]:
print(example2.shape)
#Using the shape method to print the dimension of the data handling the array.
#The result is (4,), i.e it has 1 dimension and the one dimention has 4 element int he array 

(4,)


In [7]:
print(example2.dtype) #the dtype method print the datatype of the value/variable associated with it.

int32


In [8]:
print(example2.ndim) #Will print the no of dimension of the example2 variable with ndim

1


In [9]:
#print(help(np)) #THis will print the documentation of the numpy package

##  1. NumPy Arrays

In [10]:
my_list = [0,1,2,3] #Storing python list here
my_list

[0, 1, 2, 3]

In [13]:
np.array(my_list) #Used this to convert the python list to a numpy array

array([0, 1, 2, 3])

'''While the python list and numpy array look so alike, there are some differences, part of which is that,
* Numpy Array is super fast in use case, so its more efficient
* Most of ML packages like SKlearn we would be using uses numpy array and not python list
* Is it important to be careful when usng those array and lists to avoid unnecessary errors
'''

In [18]:
my_matrix = [[1,2,3],
            [4,5,6]]
#Just created a matrix, as seeon
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [20]:
np.array(my_matrix) #Transforming the matrix to a numpy array using rhe array() method

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Built in methods
# np.arange() :Return evenly spaced values within a given interval.
#NB arange not arrange, i will like to pronounce 'a range', its a method
np.arange(0,4) #it will provide a numpy array that will range from 0 to n-1, in this case 3

array([0, 1, 2, 3])

In [15]:
np.arange(0,10,3) #Works closly like the code cell above, but here, it takes 3 parameter
#The 3rd parameter is the step(i.e interval) that should be btw the range os start and stop

array([0, 3, 6, 9])

In [23]:
# Zeros method:Return a new numpy array of given shape and type, filled with zeros.
#First parameter is shape so, return a array with 5 zero
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((5,5)) #Same as above but 2 parameter here, second is column  shape size
#Nb The 2 parameter are in a bracket, showing the bracket row and column size

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
# ones method: Return a new array of given shape and type, filled with ones.
np.ones(5) #works like the zero method with one parameter

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((5,5)) #Same as above but 2 parameter here, second is column  shape size
#Nb The 2 parameter are in a bracket, showing the bracket row and column size

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# linspace : Return evenly spaced numbers over a specified interval.
#With linespace method, the Stop value is included in the result (i.e it doesnt follow the n-1 rule)
#parameter is (start, stop, num (i.enum is how many numbers should be resulted out of the inverval, defualyis 50))
np.linspace(0,20,30) #i.e generate 30 numbers betweek 0 to 20 with the spaced eqqually

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [41]:
# eye: Creates identity matrix i.e Return a 2-D array with ones on the diagonal and zeros elsewhere.
#while passing other arguments are optional, the first is isn't, its int and deletermine the number of rows and column
np.eye(10) #Return a matrix with diagonal 1 and others being zero with 10 rows and column

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [53]:
# rand : create random samples from in a given shape passed as argument (from uniform disctribution)
np.random.rand(5)

array([0.90462773, 0.44025356, 0.56338684, 0.77341365, 0.51713061])

In [54]:
np.random.rand(5,5) #If with 2 arguments, it determine the dimension of the matrix with random values all across

array([[0.84415391, 0.78059466, 0.76301274, 0.03338527, 0.71156264],
       [0.4677268 , 0.22512994, 0.41878204, 0.28322913, 0.03974648],
       [0.30461755, 0.60793904, 0.57271285, 0.75041056, 0.84499852],
       [0.63791415, 0.534503  , 0.90580234, 0.39796754, 0.10563125],
       [0.86062656, 0.72041154, 0.09888075, 0.03645101, 0.44445321]])

In [48]:
# randn : create random samples (from standard normal distribution)
np.random.randn(5)

array([-0.08069599, -0.21861574, -0.62581801, -0.23757178, -1.42532927])

In [56]:
np.random.randn(5,5) #i.e create 5 array with each of them having 5 element

array([[ 0.42112304, -1.34446442,  0.68087462, -0.6695291 ,  0.65760305],
       [ 0.47223334, -0.18214633, -0.60730864,  1.00215752,  0.48852851],
       [ 0.98404806, -1.73224237, -0.79145875,  2.53475496,  1.18694767],
       [-0.15380201,  1.22918242,  0.43500551,  1.00711923, -0.2969141 ],
       [ 1.28361259, -0.59847284,  0.80016164,  0.46437005, -2.35823443]])

In [61]:
# randit(a,b) : create random sample of integers from a (including a) to b (excluding b (i.e n-1 rule)) 
np.random.randint(1,5) #Will generate random integer number btw 1 to 4

2

In [62]:
np.random.randint(1,5,20) #3rd argument means, make it an array of 20 element
#So, the 3rd parameter is the size of the array to be created with randon integer numbers

array([1, 1, 4, 1, 4, 1, 3, 1, 4, 2, 2, 3, 3, 4, 1, 1, 4, 2, 2, 2])

In [63]:
# seed is used to fix the random state. passing a value to it meens it the random state will be constant to that number
#therefore it will keep generating the random number
#Advantage is that it can help maintain generating a specific number 
np.random.seed(100) 
np.random.randn(5)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [67]:
np.random.seed(100)
np.random.randn(4)
#As will be seen, if this column is ran 100 times, so far the constant state value is same, 
#It will keep generating same numbers all through the times.

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604])

In [68]:
# Built in methods
# np.arange() :Return evenly spaced values within a given interval.
#NB 'arange' not 'arrange', i will like to pronounce 'a range', its a method
my_array = np.arange(1,10)
my_array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# reshape methos to reshape the array into specified dimension (row and column)
new_array = my_array.reshape(3,3)
new_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
new_array.shape #A method used to check the shape of an array

#in this case
# 3,3 means 3 rows and 3 columns
#That made the dimentions 3 by 3

(3, 3)

In [72]:
new_array.dtype
#the dtype method print the datatype of the value/variable associated with it.

dtype('int32')

In [73]:
type(new_array) #Used the type function to check the datatype of the variable passed as parameter
#Works almost like same of the dtype 

numpy.ndarray

In [75]:
my_array = np.append(my_array, [100,-100]) #Using the append method to add values to the end of existing array
#The variable of the existing array is passed as first parameter
#Second parameter is the value to append, it can be a python list, anothe  
my_array

my_array2 = np.append(my_array, my_array)
my_array2

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,  100, -100,
        100, -100,    1,    2,    3,    4,    5,    6,    7,    8,    9,
        100, -100,  100, -100])

In [79]:
my_array.max() #Return the element with the maximum value in the arry

100

In [80]:
my_array.argmax() #Return the index of maximum number in the number array 

9

In [81]:
my_array.min() #Return the element with the mainimum value in the arry

-100

In [82]:
#Return the index of manimum number in the number array my_array.argmin()

## 2. Numpy indexing and extraction

In [83]:
my_array

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,  100, -100,
        100, -100])

In [84]:
# extraction is very similar to list extraction
my_array[1] #Similar to like string indexing

2

In [85]:
my_array[6:9] #Similar to like string slicing, note it use the n-1 idea for the stop parameter

array([7, 8, 9])

In [88]:
# With NumPy arrays, you can broadcast a single value across a larger set of values. 
#This is not possible using python lists. 
#THerefore another advantge of numpy array over the python list 
my_array[0:5]=100 #SO this changed the element in index 0 to 4 to 100
my_array

array([ 100,  100,  100,  100,  100,    6,    7,    8,    9,  100, -100,
        100, -100])

In [89]:
my_list = list(range(1,10)) #Lets type the idea here with list first
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
my_list[0:5] #WIth this to access the element in index - to 4

[1, 2, 3, 4, 5]

In [91]:
my_list[0:2]=100 #hahaha, raised an error, so, broadcasting can't work here

TypeError: can only assign an iterable

In [92]:
my_list[0:2]=[100,100,100] #THough it can work like this, i mean on python list
#i.e specify the value of every element accessed through index
my_list

[100, 100, 100, 3, 4, 5, 6, 7, 8, 9]

In [95]:
# matrix: Note that matrix indexing in python is slightly different than R, Matlab or other programmings. 

my_matrix= np.arange(0,6).reshape(2,3)
# used the arange() to create a numpy array that ranges from 0 to 6
# used the .reshape() to reshape it from its default 1 dimentional to whatever is passed as parameter
print(my_matrix)

my_matrix.shape #Used this to find the shape

[[0 1 2]
 [3 4 5]]


(2, 3)

In [96]:
# Format is matrix[row][col] or matrix[row,col]

# extracting the first row
my_matrix[0]

array([0, 1, 2])

In [108]:
# extracting the first column
my_matrix[:,0] #Here, the index square bracket is parameter is reperated with comma, 
#Before the comman, the : shows that from beggining to end of row
#while the value after the comma tells that the index of column should be displayed

array([0, 3])

In [122]:
#code in the cell above is also same as 
my_matrix[:][2:2]
#following the format syntax matrix[row][col] or matrix[row,col]

array([], shape=(0, 3), dtype=int32)

In [113]:
#Here is another example
my_matrix[:,2] #This will show the entire row and the third column (i used value 2 to call third column because its index is 1)

array([2, 5])

In [123]:
my_matrix[0][1] == my_matrix[0,1]  #to confirm if the result of both matrix indexing are equal

True

In [124]:
my_matrix[:2,1:] #ANother matrix indexing.

array([[1, 2],
       [4, 5]])

Use google image to get help on "numpy array indexing" will show lots of images and how they can be used to acess cells in a matrix, they are severel of them in the image section after browsing.
Its important to look at them closely to understand the happens there as its very important to learn and master

### Extracting with conditional selection


In [125]:
my_array

array([ 100,  100,  100,  100,  100,    6,    7,    8,    9,  100, -100,
        100, -100])

In [126]:
my_array > 50

array([ True,  True,  True,  True,  True, False, False, False, False,
        True, False,  True, False])

In [105]:
my_array[my_array>50] #THis result to add element whose value are higher than 50 to the new list formed

array([100, 100, 100, 100, 100, 100])

This is another advantage of using arrays instead of lists. You cannot simply apply the comparison operators to a list. You must use filter() function instead. 

In [139]:
list(filter(lambda x: x>50, my_array)) #THe lambda here is used to set the condition. 
#like: if x is greater then 50, then pass (i.e create) my_arry
#If it is a list this is what we would have done which is a longer process

[100, 100, 100, 100, 100, 100, 100]

In [128]:
my_matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
my_matrix > 1

array([[False, False,  True],
       [ True,  True,  True]])

In [132]:
my_matrix[my_matrix > 1] #THis will only make the element in the matriz and greater than 1 and create another list out of it
# the shape is not reserved though!

array([2, 3, 4, 5])

## 3. Numpy operations - Inter-Operability (Focus here) 

In [133]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [135]:
arr + arr #THis add the element together by matching the elements in d same order 

array([0, 2, 4, 6, 8])

In [137]:
arr ** arr #Here the exponential operation is performed here on the element in order

array([  1,   1,   4,  27, 256])

In [142]:
arr/arr 
#THis resulted to a warning, not really an erro, the code run but might not lead to good result.
# While it's not a crime having warning in our codes, it not so good to have them too.
# Removing them is better, having warnings there shows that it need attention
#Looking at the code, it will execute as [(0/0),(1/1),(2/2)(3/3),(4/4)]
# bcus i knew arithmetically, zero divided by zero isn't possible and wont lead to an integer value.
# So for such, it  can raise worning which is seen below

C:\Users\BHEEZ\AppData\Local\Temp\ipykernel_27076\1740650407.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.])

In [147]:
1/arr #ALso here, warning is raised, it displayed result but yet, something isn't proper, which could be (1/0)

C:\Users\BHEEZ\AppData\Local\Temp\ipykernel_27076\2994218977.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr #ALso here, warning is raised, it displayed result but yet, something isn't proper, which could be (1/0)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [188]:
data1 = np.array([[9,3,1,3],[2,4,7,9]])
data2 = np.array([[7,2,8,1],[3,5,0,6]])                 

In [189]:
data1  + data2 

array([[16,  5,  9,  4],
       [ 5,  9,  7, 15]])

In [190]:
data1 * data2

array([[63,  6,  8,  3],
       [ 6, 20,  0, 54]])

In [192]:
5 / data2 #Raised a waining

C:\Users\BHEEZ\AppData\Local\Temp\ipykernel_27076\607227290.py:1: RuntimeWarning: divide by zero encountered in divide
  5 / data2 #Raised a waining


array([[0.71428571, 2.5       , 0.625     , 5.        ],
       [1.66666667, 1.        ,        inf, 0.83333333]])

In [148]:
# Square Roots
np.sqrt(arr) #using the sqrt function on an array returns the squareroot of values in the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [149]:
# Exponential
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [150]:
# Natural Logarithm
np.log(arr) #Also raises warning

C:\Users\BHEEZ\AppData\Local\Temp\ipykernel_27076\976472134.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #Also raises warning


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [151]:
# summary statistics on arrays
arr

array([0, 1, 2, 3, 4])

In [152]:
arr.sum() #Sum all element together

10

In [154]:
arr.mean() #Calculate the mean of the array

2.0

In [155]:
arr.var() #Calculate the variance of the array

2.0

In [156]:
arr.std() #Calculate the standard variance of the array

1.4142135623730951

# I am focusing more on this
As directed by Hamoye, their material continues here

In [166]:
#There are also some inbuilt functions that can be used to initialize numpy 
#which include empty(), zeros(), ones(), full(), random.random().

np.random.random((2,3)) #Generate array with dimension as passed paramter with random values for the elemnnt of the array

array([[0.89132195, 0.20920212, 0.18532822],
       [0.10837689, 0.21969749, 0.97862378]])

In [167]:
np.zeros((2,3)) #Explained this earlier
#the zeros function Return a new array of given shape and type, filled with zeros.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [169]:
np.ones((2,3)) #Explained this earlier
#Return a new array of given shape and type, filled with ones.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [173]:
np.identity(3)
#Return the identity array.
#The identity array is a square array with ones on the main diagonal.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [178]:
np.empty((3,2))
#The empty function Return a new array of given shape and type, without initializing entries.

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [187]:
np.full((2,3),10)
#Return a new array of given shape and type, filled with `fill_value`.
#As here, seconnd argument i.e fill_value is 10 here, means create an array of (2,3) full on value 10 as element

array([[10, 10, 10],
       [10, 10, 10]])

# Indexing With Arrays & Using Arrays for Data Processing

In [246]:
# The elements in the example arrays here can be accessed by indexing like lists in Python such that:

array_ind1 = np.array([[9,3,1,3],[2,4,7,9]])
array_ind2 = np.array([[7,2,8,1],[3,5,0,6]])


array_ind3 = np.array([[9,3,1,3],
                       [2,4,7,9],
                       [7,2,8,1],
                       [3,5,0,6]])

In [247]:
#Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing.
array_ind1[0:1]

array([[9, 3, 1, 3]])

In [198]:
array_ind2[0,1]

2

In [203]:
array_ind3.shape

(4, 4)

In [245]:
array_ind3[:4,1:3] #THis takes sometime to get right, a lot to understand there
#check closely next time to understand how ti works quickly

array([[3, 1],
       [4, 7],
       [2, 8],
       [5, 0]])

In [254]:
#There are other advanced methods of indexing which are shown below. #THis is called Integer Indexing
array_ind3[[2,2],[3,1]]
#this type of indexing is called INTEGER INDEXING
#It is used to select element in the array at (element_row,element_column)

array([1, 2])

In [257]:
#So, lets access element 5, 8 and 9 form the array_ind3 array
#Since the  index for 5 is  (3,1)
# 8 is (2,2)
# 9 is (1,3)
#We can index them like
array_ind3[[3,2,1],[1,2,3]] 
#i.e array_ind3[[element 5 row,element 8 row,element 9 row],[element 5 column,element 8 column,element 9 column]]

array([5, 8, 9])

In [259]:
#Another is BOOLEAN INDEXING 
array_ind3[array_ind3<5] 
#i.e Using conditional operator to set condition to call only element less than 5 from array_ind3 

array([3, 1, 3, 2, 4, 2, 1, 3, 0])

## Axis Logic (I ignored this for now)
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 is the vertical axis (elements on the rows), and axis 1 is the horizonal axis (elements on the columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [158]:
my_matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [159]:
# axis 0 (zero) is doing a vertical operation (element on rows), 
#and axis 1 a horizonal one (element on column) 
# again, note that the logic is different from R, Matlab or etc
my_matrix.sum(axis=0)

array([3, 5, 7])

In [160]:
my_matrix.sum(1) #From documentation, first parameter is axis, i.e here, axis=1

array([ 3, 12])

In [161]:
my_matrix * my_matrix  # note that this is not a matrix multiplication

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [162]:
# To do a matrix multiplication use np.dot (equivalent to %*% in R)
np.dot(my_matrix,my_matrix.T)

array([[ 5, 14],
       [14, 50]])

In [163]:
# inverse of a matrix
A = np.array([[1,2],[3,4]]) 
A

array([[1, 2],
       [3, 4]])

In [260]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# File Input and Output With Arrays
Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() respectively. This can also be done with text files with text files using loadtxt() and savetxt().
